// Generated by scripts/gen-types.ts from the live database schema. Do not edit by hand.
// Regenerate with: npm run db:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      clients: {
        Row: {
          id: string
          name: string
          phone: string | null
          alt_phone: string | null
          company: string | null
          address: string | null
          city: string | null
          notes: string | null
          is_seed: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          phone?: string | null
          alt_phone?: string | null
          company?: string | null
          address?: string | null
          city?: string | null
          notes?: string | null
          is_seed?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          phone?: string | null
          alt_phone?: string | null
          company?: string | null
          address?: string | null
          city?: string | null
          notes?: string | null
          is_seed?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "clients_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      order_finance: {
        Row: {
          order_id: string
          order_amount: number | null
          delivery_charges: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          order_id: string
          order_amount?: number | null
          delivery_charges?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          order_id?: string
          order_amount?: number | null
          delivery_charges?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_finance_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: true
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_finance_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          sort_order: number
          name: string
          quantity: number
          size: string | null
          sheet_code: string | null
          metal_colour: string | null
          pc: string | null
          rack: string | null
          fabric: string | null
          leather: string | null
          foam: string | null
          railing: string | null
          lock: string | null
          note: string | null
          image_path: string | null
          status: Database["public"]["Enums"]["item_status"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          sort_order?: number
          name: string
          quantity: number
          size?: string | null
          sheet_code?: string | null
          metal_colour?: string | null
          pc?: string | null
          rack?: string | null
          fabric?: string | null
          leather?: string | null
          foam?: string | null
          railing?: string | null
          lock?: string | null
          note?: string | null
          image_path?: string | null
          status?: Database["public"]["Enums"]["item_status"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          sort_order?: number
          name?: string
          quantity?: number
          size?: string | null
          sheet_code?: string | null
          metal_colour?: string | null
          pc?: string | null
          rack?: string | null
          fabric?: string | null
          leather?: string | null
          foam?: string | null
          railing?: string | null
          lock?: string | null
          note?: string | null
          image_path?: string | null
          status?: Database["public"]["Enums"]["item_status"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_notes: {
        Row: {
          id: string
          order_id: string
          body: string
          author_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          body: string
          author_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          body?: string
          author_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_notes_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_notes_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          id: string
          order_number: string
          bill_number: string | null
          client_id: string
          delivery_address: string | null
          order_date: string
          delivery_deadline: string
          status: Database["public"]["Enums"]["production_status"]
          delivered_at: string | null
          responsible_id: string | null
          special_instructions: string | null
          created_by: string | null
          is_archived: boolean
          archived_at: string | null
          is_seed: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_number?: string
          bill_number?: string | null
          client_id: string
          delivery_address?: string | null
          order_date?: string
          delivery_deadline: string
          status?: Database["public"]["Enums"]["production_status"]
          delivered_at?: string | null
          responsible_id?: string | null
          special_instructions?: string | null
          created_by?: string | null
          is_archived?: boolean
          archived_at?: string | null
          is_seed?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_number?: string
          bill_number?: string | null
          client_id?: string
          delivery_address?: string | null
          order_date?: string
          delivery_deadline?: string
          status?: Database["public"]["Enums"]["production_status"]
          delivered_at?: string | null
          responsible_id?: string | null
          special_instructions?: string | null
          created_by?: string | null
          is_archived?: boolean
          archived_at?: string | null
          is_seed?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_responsible_id_fkey"
            columns: ["responsible_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          id: string
          order_id: string
          amount: number
          paid_on: string
          method: Database["public"]["Enums"]["payment_method"]
          note: string | null
          recorded_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          amount: number
          paid_on?: string
          method?: Database["public"]["Enums"]["payment_method"]
          note?: string | null
          recorded_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          amount?: number
          paid_on?: string
          method?: Database["public"]["Enums"]["payment_method"]
          note?: string | null
          recorded_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_recorded_by_fkey"
            columns: ["recorded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          full_name: string
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
          is_active: boolean
          is_seed: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name: string
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          is_active?: boolean
          is_seed?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          is_active?: boolean
          is_seed?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      settings: {
        Row: {
          id: number
          due_soon_days: number
          start_warning_days: number
          not_started_grace_days: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          id?: number
          due_soon_days?: number
          start_warning_days?: number
          not_started_grace_days?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          id?: number
          due_soon_days?: number
          start_warning_days?: number
          not_started_grace_days?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      status_history: {
        Row: {
          id: number
          order_id: string
          from_status: Database["public"]["Enums"]["production_status"] | null
          to_status: Database["public"]["Enums"]["production_status"]
          changed_by: string | null
          changed_at: string
        }
        Insert: {
          id?: never
          order_id: string
          from_status?: Database["public"]["Enums"]["production_status"] | null
          to_status: Database["public"]["Enums"]["production_status"]
          changed_by?: string | null
          changed_at?: string
        }
        Update: {
          id?: never
          order_id?: string
          from_status?: Database["public"]["Enums"]["production_status"] | null
          to_status?: Database["public"]["Enums"]["production_status"]
          changed_by?: string | null
          changed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "status_history_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "status_history_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      order_balances: {
        Row: {
          order_id: string
          client_id: string
          status: Database["public"]["Enums"]["production_status"]
          is_archived: boolean
          order_amount: number | null
          delivery_charges: number
          grand_total: number | null
          received: number
          remaining: number | null
        }
        Relationships: []
      }
      order_overview: {
        Row: {
          id: string
          order_number: string
          bill_number: string | null
          client_id: string
          client_name: string
          client_phone: string | null
          client_phone_digits: string
          client_company: string | null
          client_city: string | null
          delivery_address: string | null
          order_date: string
          delivery_deadline: string
          status: Database["public"]["Enums"]["production_status"]
          delivered_at: string | null
          responsible_id: string | null
          responsible_name: string | null
          special_instructions: string | null
          is_archived: boolean
          archived_at: string | null
          is_seed: boolean
          created_by: string | null
          created_at: string
          updated_at: string
          item_count: number
          ready_count: number
          total_quantity: number
          item_preview: string[]
          days_left: number
          attention_level: Database["public"]["Enums"]["attention_level"] | null
          attention_rank: number
        }
        Relationships: []
      }
    }
    Functions: {
      attention_rank: {
        Args: { p_level: Database["public"]["Enums"]["attention_level"] }
        Returns: number | null
      }
      compute_attention: {
        Args: { p_status: Database["public"]["Enums"]["production_status"]; p_is_archived: boolean; p_deadline: string; p_received_on: string; p_today: string; p_due_soon_days: number; p_start_warning_days: number; p_grace_days: number }
        Returns: Database["public"]["Enums"]["attention_level"] | null
      }
      dashboard_summary: {
        Args: never
        Returns: { overdue: number | null; due_soon: number | null; needs_to_start: number | null; on_track: number | null; in_production: number | null; ready_for_delivery: number | null; delivered_this_month: number | null; outstanding_balance: number | null; orders_with_balance: number | null }[]
      }
      save_order: {
        Args: { payload: Json }
        Returns: string
      }
    }
    Enums: {
      attention_level: "overdue" | "due_soon" | "needs_to_start" | "on_track"
      item_status: "pending" | "in_production" | "ready"
      payment_method: "cash" | "bank_transfer" | "cheque" | "other"
      production_status: "new" | "in_production" | "ready_for_delivery" | "delivered" | "on_hold" | "cancelled"
      user_role: "admin" | "staff"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]

export const Constants = {
  public: {
    Enums: {
      attention_level: ["overdue", "due_soon", "needs_to_start", "on_track"],
      item_status: ["pending", "in_production", "ready"],
      payment_method: ["cash", "bank_transfer", "cheque", "other"],
      production_status: ["new", "in_production", "ready_for_delivery", "delivered", "on_hold", "cancelled"],
      user_role: ["admin", "staff"],
    },
  },
} as const
